# Generated by Django 2.1.1 on 2018-09-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fk', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('cookie', models.TextField()),
                ('header', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='log_a',
            fields=[
                ('user', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qian.user'),
        ),
    ]
