# Generated by Django 2.1.1 on 2018-09-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0002_log_a_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.TextField(default='ss'),
            preserve_default=False,
        ),
    ]
