# Generated by Django 2.1.1 on 2018-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0003_data_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_a',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
