# Generated by Django 2.1.1 on 2018-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0004_auto_20180911_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log_a',
            name='data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
