# Generated by Django 2.1.1 on 2018-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0005_auto_20180911_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_a',
            name='name',
            field=models.CharField(default='未设置', max_length=200),
            preserve_default=False,
        ),
    ]
