# Generated by Django 2.1.1 on 2018-09-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0006_log_a_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
