# Generated by Django 2.1.1 on 2018-09-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0008_auto_20180913_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yingyong',
            field=models.IntegerField(default=0),
        ),
    ]
