# Generated by Django 2.1.1 on 2018-09-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qian', '0009_user_yingyong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yingyong',
            field=models.IntegerField(default=2),
        ),
    ]
